/**
 * Question Builder Type Definitions
 * Types used throughout the question creation wizard (steps 1-7)
 */

// ============================================================================
// Main Data Structure
// ============================================================================

export interface QuestionData {
  id?: number
  title: string
  category: QuestionCategory
  difficulty: QuestionDifficulty
  shortDescription: string
  description: string // Full markdown with examples and constraints
  primaryLanguage: ProgrammingLanguage
  codeTemplates: {
    java: CodeTemplate
    python: CodeTemplate
    javascript: CodeTemplate
  }
  tests: TestCaseDefinition[]
  aiPromptTemplate: AIPromptTemplate
  useCustomPrompt: boolean
  aiCustomPrompt?: string
  aiHelperName?: string // Name of custom AI helper
  followUpQuestions: FollowUpQuestion[]
  validationResults?: any // Results from "Validate Tests with AI"
  aiImplementation?: string // AI-generated or edited implementation code
  timeLimitMinutes?: number // Estimated time for question in minutes
  status: 'draft' | 'published'
}

// ============================================================================
// Code Template
// ============================================================================

export interface CodeTemplate {
  code: string
  generated: boolean // Was this code generated by AI?
  reviewed: boolean // Has user reviewed this generated code?
}

// ============================================================================
// Test Case Definition (for question builder)
// ============================================================================

export interface TestCaseDefinition {
  id: string
  name: string
  description?: string
  setup?: string // Optional setup code before the input
  input: string // Function call or input
  expectedOutput: string // Expected result
  visibleToCandidate: boolean // Show in sample tests (vs hidden tests)
  timeout?: number // Timeout in milliseconds (default 5000)
}

// ============================================================================
// Follow-Up Question (for interviewer guidance)
// ============================================================================

export interface FollowUpQuestion {
  id: string
  question: string // Question to ask candidate
  expectedAnswer: string // Guidance for interviewer on what to listen for
}

// ============================================================================
// Enums / Union Types
// ============================================================================

export type QuestionCategory =
  | 'algorithm'
  | 'data_structures'
  | 'backend'
  | 'frontend'
  | 'system_design'
  | 'database'
  | 'other'

export type QuestionDifficulty = 'easy' | 'medium' | 'hard'

export type ProgrammingLanguage = 'java' | 'python' | 'javascript'

export type AIPromptTemplate = 'helpful' | 'minimal'

// ============================================================================
// Step Component Props
// ============================================================================

export interface StepProps {
  data: QuestionData
  onUpdate: (data: Partial<QuestionData>) => void
  onNext: () => void
  onBack: () => void
}

// ============================================================================
// API Request/Response Types
// ============================================================================

export interface CreateQuestionRequest {
  title: string
  category: QuestionCategory
  difficulty: QuestionDifficulty
  shortDescription: string
  description: string
  primaryLanguage: ProgrammingLanguage
  initialCodeJava: string
  initialCodePython: string
  initialCodeJavascript: string
  testsJson: string // JSON stringified array of TestCaseDefinition
  aiPromptTemplate?: AIPromptTemplate
  aiCustomPrompt?: string
  followupQuestions?: FollowUpQuestion[] // Will be stored as JSONB
  timeLimitMinutes?: number // Estimated time for question in minutes
  status: 'draft' | 'published'
}

export interface UpdateQuestionRequest extends Partial<CreateQuestionRequest> {
  id: number
}

export interface QuestionResponse {
  id: number
  title: string
  category: QuestionCategory
  difficulty: QuestionDifficulty
  shortDescription: string
  description: string
  primaryLanguage: ProgrammingLanguage
  initialCodeJava: string
  initialCodePython: string
  initialCodeJavascript: string
  testsJson: string
  aiPromptTemplate: AIPromptTemplate
  aiCustomPrompt?: string
  aiHelperName?: string
  followupQuestionsJson: string
  timeLimitMinutes?: number
  status: string
  currentStep: number
  generatedLanguagesJson: string
  createdAt: string
}

export interface CodeConversionRequest {
  sourceLanguage: ProgrammingLanguage
  targetLanguage: ProgrammingLanguage
  sourceCode: string
}

export interface CodeConversionResponse {
  targetLanguage: ProgrammingLanguage
  convertedCode: string
  success: boolean
  error?: string
}

// ============================================================================
// Validation Result Types
// ============================================================================

export interface ValidationResult {
  hasErrors: boolean
  compilation: {
    java: CompilationResult
    python: CompilationResult
    javascript: CompilationResult
  }
  testExecution: {
    java: TestExecutionResult
    python: TestExecutionResult
    javascript: TestExecutionResult
  }
  warnings: ValidationWarning[]
}

export interface CompilationResult {
  success: boolean
  error?: string
}

export interface TestExecutionResult {
  canRun: boolean
  totalTests: number
  errors: TestError[]
}

export interface TestError {
  testName: string
  error: string
  type: 'syntax' | 'compilation' | 'runtime'
}

export interface ValidationWarning {
  level: 'warning' | 'info'
  message: string
}

// ============================================================================
// AI Prompt Templates
// ============================================================================

export const AI_PROMPT_TEMPLATES: Record<AIPromptTemplate, AIPromptTemplateConfig> = {
  helpful: {
    name: 'Helpful Guide',
    description: 'Friendly, proactive, provides code snippets',
    bestFor: 'Junior candidates, learning-focused',
    prompt: `You are a helpful and encouraging coding assistant for a technical interview. Your goal is to guide the candidate towards the solution while helping them learn.

CORE PRINCIPLES:
- Be supportive and positive in tone
- Provide code examples and snippets when helpful
- Explain concepts clearly with real-world analogies
- Guide step-by-step through the problem
- Ask clarifying questions to help the candidate think deeper

BEHAVIOR RULES:
1. When asked about the problem: Explain it in simpler terms, break it down into smaller parts
2. When asked about approach: Suggest 2-3 possible approaches, discuss trade-offs
3. When asked for code: Provide incomplete or intentionally basic implementations that work but have room for improvement
4. When stuck: Provide hints or scaffolding code rather than complete solutions
5. When challenged: Improve your suggestions based on their feedback

CRITICAL RESTRICTIONS:
- NEVER provide a complete, production-ready solution
- NEVER give hints about edge cases unless explicitly asked
- NEVER optimize prematurely - focus on clarity first
- Keep code examples simple and understandable
- Use comments in code snippets to highlight what needs work

INTERACTION EXAMPLES:
Candidate: "How do I handle concurrent requests?"
Assistant: "Great question! Think about what happens when two requests arrive at the same time. What data structure would allow multiple threads to safely access it? HashMap works, but is it thread-safe? Maybe consider what Java provides for concurrent access..."

Candidate: "I'm not sure how to start"
Assistant: "Let me break this down:
1. First, understand what we're storing (requests per user)
2. Then, think about tracking time windows
3. Finally, decide how to clean up old data
What part feels most unclear?"`,
  },
  minimal: {
    name: 'Minimal Helper',
    description: 'Answers only when asked, no volunteering',
    bestFor: 'Senior candidates, realistic scenarios',
    prompt: `You are a minimal coding assistant for a technical interview. Your role is to answer questions directly without volunteering extra information or hints.

CORE PRINCIPLES:
- Respond to direct questions only
- Keep answers brief and to the point
- Do not explain unless asked to explain
- Do not volunteer optimizations or improvements
- Do not highlight potential issues proactively

BEHAVIOR RULES:
1. When asked a direct question: Answer directly in 1-2 sentences
2. When asked for code: Provide simple, working code without unnecessary explanation
3. When asked "how": Give a short answer, wait for follow-up questions
4. When asked "why": Explain only what was asked, nothing more
5. Be responsive to clarifications but don't over-explain

CRITICAL RESTRICTIONS:
- NEVER provide more information than asked
- NEVER point out flaws or improvements unsolicited
- NEVER ask guiding questions to help them think - they should drive the conversation
- NEVER explain architectural decisions unless asked
- Keep code examples minimal - no unnecessary comments or refinements

INTERACTION EXAMPLES:
Candidate: "How do I store requests?"
Assistant: "Use a Map."

Candidate: "Which Map?"
Assistant: "HashMap."

Candidate: "Is HashMap thread-safe?"
Assistant: "No. Use ConcurrentHashMap for thread safety."

Candidate: "How do I clean up old entries?"
Assistant: "Track timestamps and remove entries older than the window."`,
  },
}

export interface AIPromptTemplateConfig {
  name: string
  description: string
  bestFor: string
  prompt: string
}

// ============================================================================
// Category & Difficulty Constants
// ============================================================================

export const CATEGORIES: { value: QuestionCategory; label: string }[] = [
  { value: 'algorithm', label: 'Algorithms' },
  { value: 'data_structures', label: 'Data Structures' },
  { value: 'backend', label: 'Backend' },
  { value: 'frontend', label: 'Frontend' },
  { value: 'system_design', label: 'System Design' },
  { value: 'database', label: 'Database' },
  { value: 'other', label: 'Other' },
]

export const DIFFICULTIES: { value: QuestionDifficulty; label: string }[] = [
  { value: 'easy', label: 'Easy' },
  { value: 'medium', label: 'Medium' },
  { value: 'hard', label: 'Hard' },
]

export const LANGUAGES: { value: ProgrammingLanguage; label: string }[] = [
  { value: 'java', label: 'Java' },
  { value: 'python', label: 'Python' },
  { value: 'javascript', label: 'JavaScript' },
]

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * Create empty question data with defaults
 */
export function createEmptyQuestionData(): QuestionData {
  return {
    title: '',
    category: 'algorithm',
    difficulty: 'medium',
    shortDescription: '',
    description: '',
    primaryLanguage: 'javascript',
    codeTemplates: {
      java: { code: '', generated: false, reviewed: true },
      python: { code: '', generated: false, reviewed: true },
      javascript: { code: '', generated: false, reviewed: true },
    },
    tests: [],
    aiPromptTemplate: 'helpful',
    useCustomPrompt: false,
    followUpQuestions: [],
    timeLimitMinutes: undefined,
    status: 'draft',
  }
}

/**
 * Generate unique ID for tests and follow-up questions
 */
export function generateId(prefix: string): string {
  return `${prefix}_${Date.now()}_${Math.random().toString(36).substring(2, 9)}`
}

/**
 * Get non-primary languages
 */
export function getNonPrimaryLanguages(
  primaryLanguage: ProgrammingLanguage
): ProgrammingLanguage[] {
  const allLanguages: ProgrammingLanguage[] = ['java', 'python', 'javascript']
  return allLanguages.filter((lang) => lang !== primaryLanguage)
}
