/**
 * Question Builder Type Definitions
 * Types used throughout the question creation wizard (steps 1-7)
 */

// ============================================================================
// Main Data Structure
// ============================================================================

export interface QuestionData {
  id?: number
  title: string
  category: QuestionCategory
  difficulty: QuestionDifficulty
  shortDescription: string
  description: string // Full markdown with examples and constraints
  primaryLanguage: ProgrammingLanguage
  codeTemplates: {
    java: CodeTemplate
    python: CodeTemplate
    javascript: CodeTemplate
  }
  tests: TestCaseDefinition[]
  aiPromptTemplate: AIPromptTemplate
  useCustomPrompt: boolean
  aiCustomPrompt?: string
  followUpQuestions: FollowUpQuestion[]
  status: 'draft' | 'published'
}

// ============================================================================
// Code Template
// ============================================================================

export interface CodeTemplate {
  code: string
  generated: boolean // Was this code generated by AI?
  reviewed: boolean // Has user reviewed this generated code?
}

// ============================================================================
// Test Case Definition (for question builder)
// ============================================================================

export interface TestCaseDefinition {
  id: string
  name: string
  description?: string
  setup?: string // Optional setup code before the input
  input: string // Function call or input
  expectedOutput: string // Expected result
  visibleToCandidate: boolean // Show in sample tests (vs hidden tests)
  timeout?: number // Timeout in milliseconds (default 5000)
}

// ============================================================================
// Follow-Up Question (for interviewer guidance)
// ============================================================================

export interface FollowUpQuestion {
  id: string
  question: string // Question to ask candidate
  expectedAnswer: string // Guidance for interviewer on what to listen for
}

// ============================================================================
// Enums / Union Types
// ============================================================================

export type QuestionCategory =
  | 'algorithm'
  | 'data_structures'
  | 'backend'
  | 'frontend'
  | 'system_design'
  | 'database'
  | 'other'

export type QuestionDifficulty = 'easy' | 'medium' | 'hard'

export type ProgrammingLanguage = 'java' | 'python' | 'javascript'

export type AIPromptTemplate = 'helpful' | 'minimal' | 'socratic' | 'strict'

// ============================================================================
// Step Component Props
// ============================================================================

export interface StepProps {
  data: QuestionData
  onUpdate: (data: Partial<QuestionData>) => void
  onNext: () => void
  onBack: () => void
}

// ============================================================================
// API Request/Response Types
// ============================================================================

export interface CreateQuestionRequest {
  title: string
  category: QuestionCategory
  difficulty: QuestionDifficulty
  shortDescription: string
  description: string
  primaryLanguage: ProgrammingLanguage
  initialCodeJava: string
  initialCodePython: string
  initialCodeJavascript: string
  testsJson: string // JSON stringified array of TestCaseDefinition
  aiPromptTemplate?: AIPromptTemplate
  aiCustomPrompt?: string
  followupQuestions?: FollowUpQuestion[] // Will be stored as JSONB
  status: 'draft' | 'published'
}

export interface UpdateQuestionRequest extends Partial<CreateQuestionRequest> {
  id: number
}

export interface CodeConversionRequest {
  sourceLanguage: ProgrammingLanguage
  targetLanguage: ProgrammingLanguage
  sourceCode: string
}

export interface CodeConversionResponse {
  targetLanguage: ProgrammingLanguage
  convertedCode: string
  success: boolean
  error?: string
}

// ============================================================================
// Validation Result Types
// ============================================================================

export interface ValidationResult {
  hasErrors: boolean
  compilation: {
    java: CompilationResult
    python: CompilationResult
    javascript: CompilationResult
  }
  testExecution: {
    java: TestExecutionResult
    python: TestExecutionResult
    javascript: TestExecutionResult
  }
  warnings: ValidationWarning[]
}

export interface CompilationResult {
  success: boolean
  error?: string
}

export interface TestExecutionResult {
  canRun: boolean
  totalTests: number
  errors: TestError[]
}

export interface TestError {
  testName: string
  error: string
  type: 'syntax' | 'compilation' | 'runtime'
}

export interface ValidationWarning {
  level: 'warning' | 'info'
  message: string
}

// ============================================================================
// AI Prompt Templates
// ============================================================================

export const AI_PROMPT_TEMPLATES: Record<AIPromptTemplate, AIPromptTemplateConfig> = {
  helpful: {
    name: 'Helpful Guide',
    description: 'Friendly, proactive, provides code snippets',
    bestFor: 'Junior candidates, learning-focused',
    prompt: `You are a helpful coding assistant for this technical interview.

BEHAVIOR:
- Provide code snippets when asked
- Explain concepts clearly
- Guide the candidate step-by-step
- Be encouraging and supportive

IMPORTANT RESTRICTIONS:
- Never provide complete solutions
- Intentionally provide weak implementations when first asked
- Only improve when explicitly questioned
- Encourage the candidate to think through problems

EXAMPLE:
Candidate: "How should I implement thread safety?"
You: "You could use a HashMap to store the data. Here's a simple approach:
\`\`\`java
Map<String, List<Long>> requests = new HashMap<>();
\`\`\`
This should work for basic usage."

(Note: This is intentionally weak - HashMap is not thread-safe.
Candidate should catch this and ask for improvement.)`,
  },
  minimal: {
    name: 'Minimal Helper',
    description: 'Answers only when asked, no volunteering',
    bestFor: 'Senior candidates, realistic scenarios',
    prompt: `You are a minimal coding assistant for this technical interview.

BEHAVIOR:
- Answer questions directly when asked
- Do not volunteer information
- Keep responses brief
- No proactive suggestions

IMPORTANT RESTRICTIONS:
- Never provide complete solutions
- Intentionally provide weak implementations when first asked
- Only improve when explicitly questioned

EXAMPLE:
Candidate: "How should I store the data?"
You: "You can use a Map."

Candidate: "Which type of Map?"
You: "HashMap would work."

(Note: HashMap is intentionally weak for thread safety.
Wait for candidate to discover the issue.)`,
  },
  socratic: {
    name: 'Socratic Method',
    description: 'Asks questions, guides with inquiry',
    bestFor: 'Evaluating problem-solving approach',
    prompt: `You are a Socratic coding assistant for this technical interview.

BEHAVIOR:
- Respond to questions with guiding questions
- Help candidate discover answers themselves
- Encourage critical thinking
- Rarely give direct answers

IMPORTANT RESTRICTIONS:
- Never provide complete solutions
- If you must provide code, intentionally make it weak
- Use questions to reveal issues

EXAMPLE:
Candidate: "How should I implement thread safety?"
You: "Good question. What happens if two threads try to access a HashMap simultaneously? What could go wrong?"

Candidate: "I guess they could have race conditions?"
You: "Exactly. So what Java data structures are designed to handle concurrent access?"

(Guide them to discover ConcurrentHashMap themselves.)`,
  },
  strict: {
    name: 'Strict Evaluator',
    description: 'Points out issues, challenges assumptions',
    bestFor: 'Testing defensive coding, senior roles',
    prompt: `You are a strict coding assistant for this technical interview.

BEHAVIOR:
- Point out potential issues
- Challenge assumptions
- Ask probing questions
- Be direct about problems

IMPORTANT RESTRICTIONS:
- Never provide complete solutions
- Intentionally provide weak implementations when first asked
- Make candidate defend their choices

EXAMPLE:
Candidate: "I'll use a HashMap to store the requests."
You: "Are you sure a HashMap is the right choice here? What if multiple threads access it at the same time? What could go wrong?"

Candidate: "Oh, good point. Maybe ConcurrentHashMap?"
You: "That's better. Why is ConcurrentHashMap safer than HashMap for concurrent access?"`,
  },
}

export interface AIPromptTemplateConfig {
  name: string
  description: string
  bestFor: string
  prompt: string
}

// ============================================================================
// Category & Difficulty Constants
// ============================================================================

export const CATEGORIES: { value: QuestionCategory; label: string }[] = [
  { value: 'algorithm', label: 'Algorithms' },
  { value: 'data_structures', label: 'Data Structures' },
  { value: 'backend', label: 'Backend' },
  { value: 'frontend', label: 'Frontend' },
  { value: 'system_design', label: 'System Design' },
  { value: 'database', label: 'Database' },
  { value: 'other', label: 'Other' },
]

export const DIFFICULTIES: { value: QuestionDifficulty; label: string }[] = [
  { value: 'easy', label: 'Easy' },
  { value: 'medium', label: 'Medium' },
  { value: 'hard', label: 'Hard' },
]

export const LANGUAGES: { value: ProgrammingLanguage; label: string }[] = [
  { value: 'java', label: 'Java' },
  { value: 'python', label: 'Python' },
  { value: 'javascript', label: 'JavaScript' },
]

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * Create empty question data with defaults
 */
export function createEmptyQuestionData(): QuestionData {
  return {
    title: '',
    category: 'algorithm',
    difficulty: 'medium',
    shortDescription: '',
    description: '',
    primaryLanguage: 'javascript',
    codeTemplates: {
      java: { code: '', generated: false, reviewed: true },
      python: { code: '', generated: false, reviewed: true },
      javascript: { code: '', generated: false, reviewed: true },
    },
    tests: [],
    aiPromptTemplate: 'helpful',
    useCustomPrompt: false,
    followUpQuestions: [],
    status: 'draft',
  }
}

/**
 * Generate unique ID for tests and follow-up questions
 */
export function generateId(prefix: string): string {
  return `${prefix}_${Date.now()}_${Math.random().toString(36).substring(2, 9)}`
}

/**
 * Get non-primary languages
 */
export function getNonPrimaryLanguages(
  primaryLanguage: ProgrammingLanguage
): ProgrammingLanguage[] {
  const allLanguages: ProgrammingLanguage[] = ['java', 'python', 'javascript']
  return allLanguages.filter((lang) => lang !== primaryLanguage)
}
