package com.example.interviewAI.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.util.Map;

/**
 * DTO for creating a new question through the question builder wizard.
 * Maps to the 7-step question creation flow on the frontend.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class CreateQuestionRequest {

    // ========== Step 1: Basic Info ==========
    private String title; // Optional for drafts

    private String category; // 'algorithm', 'data_structures', 'backend', 'frontend', etc. - optional for drafts

    private String difficulty; // 'easy', 'medium', 'hard' - optional for drafts

    private String shortDescription; // Optional for drafts

    private Integer timeLimitMinutes; // Estimated time for question in minutes - optional

    // ========== Step 2: Problem Description ==========
    private String description; // Full markdown with examples and constraints - optional for drafts

    // ========== Step 3: Initial Code ==========
    private String primaryLanguage; // 'java', 'python', 'javascript' - optional for drafts

    private String initialCodeJava; // Optional for drafts

    private String initialCodePython; // Optional for drafts

    private String initialCodeJavascript; // Optional for drafts

    // Tracking which languages were generated by AI
    // Format: {"java": {"generated": false, "reviewed": true}, "python": {"generated": true, "reviewed": true}, ...}
    private Map<String, Map<String, Boolean>> generatedLanguages;

    // ========== Step 4: Test Cases ==========
    private String testsJson; // JSON stringified array of TestCaseDefinition - optional for drafts

    // ========== Step 5: AI Configuration + Follow-up Questions ==========
    private String aiPromptTemplate; // 'helpful', 'minimal' (defaults to 'helpful')

    private String aiCustomPrompt; // Custom prompt if provided

    private String aiHelperName; // Name of custom AI helper (e.g., "Expert Mentor")

    // Follow-up questions for interviewer guidance
    // Format: [{"id": "fq_1", "question": "...", "expectedAnswer": "..."}]
    private String followupQuestionsJson;

    // ========== Step 7: Publish ==========
    private String status = "DRAFT"; // 'DRAFT' or 'PUBLISHED' - defaults to DRAFT

    // ========== Draft Progress Tracking ==========
    private Integer currentStep; // Current step in the wizard (1-7), used to resume from where they left off

    // ========== Optional: Company-specific question ==========
    private Long companyId; // If null, question is platform-wide (for system admin only)

    /**
     * Validation helper - ensures test cases are valid JSON
     */
    public boolean isValidTestJson() {
        if (testsJson == null || testsJson.trim().isEmpty()) {
            return false;
        }
        try {
            // Simple JSON validation - in production, use Jackson to parse
            return testsJson.trim().startsWith("[") && testsJson.trim().endsWith("]");
        } catch (Exception e) {
            return false;
        }
    }
}
