package com.example.interviewAI.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.util.Map;

/**
 * DTO for creating a new question through the question builder wizard.
 * Maps to the 7-step question creation flow on the frontend.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class CreateQuestionRequest {

    // ========== Step 1: Basic Info ==========
    @NotBlank(message = "Title is required")
    private String title;

    @NotBlank(message = "Category is required")
    private String category; // 'algorithm', 'data_structures', 'backend', 'frontend', etc.

    @NotBlank(message = "Difficulty is required")
    private String difficulty; // 'easy', 'medium', 'hard'

    @NotBlank(message = "Short description is required")
    private String shortDescription;

    // ========== Step 2: Problem Description ==========
    @NotBlank(message = "Full description is required")
    private String description; // Full markdown with examples and constraints

    // ========== Step 3: Initial Code ==========
    @NotBlank(message = "Primary language is required")
    private String primaryLanguage; // 'java', 'python', 'javascript'

    @NotBlank(message = "Java code template is required")
    private String initialCodeJava;

    @NotBlank(message = "Python code template is required")
    private String initialCodePython;

    @NotBlank(message = "JavaScript code template is required")
    private String initialCodeJavascript;

    // Tracking which languages were generated by AI
    // Format: {"java": {"generated": false, "reviewed": true}, "python": {"generated": true, "reviewed": true}, ...}
    private Map<String, Map<String, Boolean>> generatedLanguages;

    // ========== Step 4: Test Cases ==========
    @NotNull(message = "Tests JSON is required")
    private String testsJson; // JSON stringified array of TestCaseDefinition

    // ========== Step 5: AI Configuration + Follow-up Questions ==========
    private String aiPromptTemplate; // 'helpful', 'minimal', 'socratic', 'strict' (defaults to 'helpful')

    private String aiCustomPrompt; // Custom prompt if provided

    // Follow-up questions for interviewer guidance
    // Format: [{"id": "fq_1", "question": "...", "expectedAnswer": "..."}]
    private String followupQuestionsJson;

    // ========== Step 7: Publish ==========
    @NotNull(message = "Status is required")
    private String status; // 'DRAFT' or 'PUBLISHED'

    // ========== Optional: Company-specific question ==========
    private Long companyId; // If null, question is platform-wide (for system admin only)

    /**
     * Validation helper - ensures test cases are valid JSON
     */
    public boolean isValidTestJson() {
        if (testsJson == null || testsJson.trim().isEmpty()) {
            return false;
        }
        try {
            // Simple JSON validation - in production, use Jackson to parse
            return testsJson.trim().startsWith("[") && testsJson.trim().endsWith("]");
        } catch (Exception e) {
            return false;
        }
    }
}
